---
threads: 60
organism: homo_sapiens
indexed: true
aligner: star # HISAT2 or STAR
refs:
  hg_release_ver: 100
  mm_release_ver: 
result_dir: results/
units: data/samples.tsv
working_dir: temp/

deseq2:
  maxfraction: "0.7"
fastp:
  qualified_quality_phred: 15
merge_PKM:
  organism: hsapiens_gene_ensembl