---
blast:
  evalue: 1e-10
  maxTargets: "1"
  outFmt: "6 qseqid evalue length mismatch salltitles"
deseq2:
  maxfraction: "0.7"
fastp:
  qualified_quality_phred: 15
filter_for_plots:
  average_samples: "yes"
  maximum_pvalue: "0.05"
  minimum_foldchange: "2"
  minimum_reads: "100"
make_plots:
  colour_of_heatmap: "c(\"white\",\"green\",\"green4\",\"violet\",\"purple\")"
  height_in_dendrogram: "1.5"
  membership_min: "0.2"
  method_of_clustering: pam
  number_of_clusters: "2"
  opt_clust_number: average_silhouette_width
# refs:
#   annotation: annotations/Petunia_axillaris_v1.6.2_proteins.mapman_annotation.txt.gz
#   genome: "ftp://ftp.ensembl.org/pub/release-100/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"
#   proteins_fasta: ""
#   transcriptome_gtf: "ftp://ftp.ensembl.org/pub/release-100/gtf/homo_sapiens/Homo_sapiens.GRCh38.100.gtf.gz"
result_dir: results/
units: samples.tsv
working_dir: temp/
threads: 60
