name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Login to Github Container Registery
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
          
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile_toCount
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

