name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Docker meta
        id: docker_meta
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile_toCount
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
        
#       - 
#         name: Set env
#         run: |
#           echo "RELEASE_VERSION=${GTHUB_REF#refs/*/v}" >> $GITHUB_ENV
#           IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
#           IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
#           echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
        
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - 
        name: Login to Github Container Registery
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
          
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile_toCount
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
#           tags: |            
#             ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_ID }}:latest
#             ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_ID }}:${{ env.RELEASE_VERSION }}

