name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

env:
  IMAGE_NAME: snakemake_rna-seq

jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        
      - 
        name: Set env
        run: echo "RELEASE_VERSION=${GTHUB_REF#refs/*/v}" >> $GITHUB_ENV
        
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - 
        name: Login to Github Container Registery
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
          
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile_toCount
          push: true
          tags: |
            IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
            
            ghcr.io/${{ github.repository_owner }}/$IMAGE_ID:latest
            ghcr.io/${{ github.repository_owner }}/$IMAGE_ID:${{ env.RELEASE_VERSION }}

