name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        
      - 
        name: Set env
        run: echo "RELEASE_VERSION=${GTHUB_REF#refs/*/v}" >> $GITHUB_ENV
        
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - 
        name: Login to Github Container Registery
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
          
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile_toCount
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/snakemake_RNA-seq:latest
            ghcr.io/${{ github.repository_owner }}/snakemake_RNA-seq:${{ env.RELEASE_VERSION }}

